services:
  mysql:
    image: mysql:5.7
    container_name: algo-mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: algo_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
      MYSQL_TCP_PORT: 3306
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
